name: Lauren Coseo
markdown: kramdown

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
permalink: /blog/:year/:month/:day/:title
